from sylva.data.__scm_version__ import __version__ # generated by pdm on build
from sylva.collector import Collector

__short_name__ = 'Sylva'
__long_name__ = f'{__short_name__} Identity Discovery'
__forge_url__ = 'https://github.com/ppfeister/sylva'
__user_agent__ = f'{__short_name__}/{__version__} ({__forge_url__})'
__author__ = 'Paul Pfeister'

__github_maintainer_url__ = 'https://github.com/ppfeister'
__github_raw_data_url__ = 'https://raw.githubusercontent.com/ppfeister/sylva/master/src/sylva/data/pgp.json'
__github_raw_schema_url__ = 'https://raw.githubusercontent.com/ppfeister/sylva/master/src/sylva/data/pgp.schema.json'

# Globals for normalization and similar functions
__url_normalization_pattern__ = r'(?:www\.|\/$|\/?\?.+)' # Match www, trailing slash, and query string

__all__ = [
    'Collector',
    '__short_name__',
    '__long_name__',
    '__forge_url__',
    '__user_agent__',
    '__author__',
]
